### ISSUE TITLE
Predefined Action

### ISSUE THREAD

**Issue by iwTao** [jneilliii/OctoPrint-OctoDashCompanion#21]
Hi,jneilliii,if I want add or adjust predefined action, such as define a new action [!reboot klipper].what should I do, or which file should I modify?

**Comment by jneilliii** [comment]
seems like that would be something that could be done as a macro within klipper and then you would just use that command as gcode in your button?

**Comment by iwTao** [comment]
> seems like that would be something that could be done as a macro within klipper and then you would just use that command as gcode in your button?

no, i just want click the button, then klipper will restart, just like i write “systemctl restart klipper”in my Raspberry PI’s terminal .so i want know how add a predefined action.

**Comment by jneilliii** [comment]
gotcha. you might find the [GCODE System Commands](https://plugins.octoprint.org/plugins/gcodesystemcommands/) plugin handy for this then. You define a custom gcode command like OCTO1 as `service restart klipper` and then configure your custom action as `OCTO1`.

**Comment by iwTao** [comment]
Tkanks for your help, i was set OCTO1 command, but i  receive `Return(GCodeSystemCommands): error`  when i send COTO1 in my octoprint terminal.

**Comment by jneilliii** [comment]
Try setting it to `sudo service restart klipper`

**Comment by iwTao** [comment]
I resolved this problem,need add "bash" in front of .sh file directory.
