### ISSUE TITLE
Companion not talking with octodash

### ISSUE THREAD

**Issue by mattfox27** [jneilliii/OctoPrint-OctoDashCompanion#23]
When i adjust the buttons like home in octodash companion its not update on octodash?  For instance im trying to change the home command from G28 to G28W however its not transferring to octodash.

**Comment by jneilliii** [comment]
For the changes to take effect you have to restart OctoDash. You can do that from the system menu in OctoPrint with the plugin installed.

**Comment by mattfox27** [comment]
OK, I thought I did restart, let me try it again
