### ISSUE TITLE
Custom Action Commands Missing

### ISSUE THREAD

**Issue by ab-tools** [jneilliii/OctoPrint-OctoDashCompanion#26]
The `OUTPUT` and `OUTPUT_PWM` custom action commands cannot be selected in the companion plug-in yet:
https://github.com/UnchartedBull/OctoDash/wiki/Custom-Actions#predefined-actions

Not a big problem, of course, as you can just enter them manually, but still wanted to mention it.

**Comment by jneilliii** [comment]
There is an RC version available that I think I have those options added in already. If you change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and update when prompted it should have those in there. If you confirm and it's working then I can release a stable version later tonight.

**Comment by ab-tools** [comment]
Thanks a lot, I can confirm this is working as expected now with version `0.0.7rc4`.
