### ISSUE TITLE
Octolight as Plugin

### ISSUE THREAD

**Issue by hennaschorre** [jneilliii/OctoPrint-OctoDashCompanion#37]
Hello,

is it possible to include the Octolight in the Octodash plugins, please?

Greetings,
hennaschorre :-)

**Comment by jneilliii** [comment]
might be able to do a toggle custom action button to do this. set the value of the button to

```
[!WEB]http://127.0.0.1/api/plugin/octolight?action=toggle 
```

**Comment by hennaschorre** [comment]
it works, thank you very much :-)
