### ISSUE TITLE
[Feature request] OctoCompanion - Plugin Enclosure - toggle command

### ISSUE THREAD

**Issue by mich0111** [jneilliii/OctoPrint-OctoDashCompanion#39]
Hello,
Can you please consider the possibility of adding a toggle command in the customize actions with the enclosure plugin ?
For example, to turn the lights on or off currently requires 2 buttons.
It would be better if in this case we could have only one.
Thanks in advance.
Kind regards.

**Comment by jneilliii** [comment]
Realistically that should be a request with the enclosure plugin and octodash directly. I won't add logic within this plugin to keep track of on/off status in order to perform the toggle function.
