### ISSUE TITLE
Add GPIO?

### ISSUE THREAD

**Issue by DocZagreus** [jneilliii/OctoPrint-OctoDashCompanion#6]
Hi!
I love this plug-in!
Do you think could be possible to create some kind of action to toggle on/off a light connected to Octoprint via GPIO?
Right now I'm using octolight to control the light and would be great to be able to create a light button on octodash :)

**Comment by jneilliii** [comment]
That is already possible with other plugins and gcode commands. You would just add those to the Custom Action. I have a Tasmota device with ws2812 on it that I control this way using my Tasmota plugin, but there are other plugins that can control just GPIO, ie enclosure, PSUControl, etc.

**Comment by DocZagreus** [comment]
I'm sorry but I'm pretty new to this "world".
How can I add a custom button using octodash companion that allows me to switch on/ff my light?

**Comment by jneilliii** [comment]
Looking at that OctoLight plugin, it looks like it doesn't support any form of gcode command for control. You may have better results with PSUControl to control that relay. It does support gcode commands to turn on and off the light. Then you would just add whatever gcode command that it uses in custom actions (I think the defaults are M80/M81, but are configurable), similar to this, replacing the gcode command with what that plugin expects.

![image](https://user-images.githubusercontent.com/5249455/117364658-2d15f400-ae8c-11eb-9c9b-69b807ec12b9.png)

**Comment by jneilliii** [comment]
You would have to have one button for on and one button for off.

**Comment by DocZagreus** [comment]
yep I was able to do it =)
Using LEDStripControl and using M150 W to turn on and M15o to turn off
thanks =)

**Comment by DocZagreus** [comment]
Just one last question...
Is there a way to resize the icons so that I can have a 2 by 4 buttons layout that fits the monitor interface without scrolling?

**Comment by jneilliii** [comment]
I'm not as familiar with the OctoDash internals to do this. It might be possible with a custom theme, but can't say I've seen one that messes with those buttons yet.
