### ISSUE TITLE
Add Display Off Function

### ISSUE THREAD

**Issue by stikako** [jneilliii/OctoPrint-OctoDashCompanion#8]
I've never posted on Github, so forgive me if this is in the wrong section. 

But in list of commands, is there any way of adding [!DISPLAYOFF] ? this way the screen doesn't need to be on all the time while printing. Tap to wake.

**Comment by jneilliii** [comment]
Unfortunately, that's not one of the available [custom actions](https://github.com/UnchartedBull/OctoDash/wiki/Custom-Actions) available in octodash. You'd have to request that over there.

**Comment by stikako** [comment]
Thank you sir, I'll bark up that tree then! lol
