### ISSUE TITLE
Add support for your MultiCamView

### ISSUE THREAD

**Issue by hawkeyexp** [jneilliii/OctoPrint-OctoDashCompanion#9]
Let's talk about here. I didn't rember that i switched from multicam to you multicamview plugin, cause multicam looses url's if you reboot octoprint without switching back to default url.
Would be nice if you can add a catch for the url's from multicamview to setup the cam via actionbutton :-)

**Comment by jneilliii** [comment]
Ah, interesting, I didn't realize there was a bug in multicam plugin and assumed that's what most people were using since my plugin isn't even registered on the official repo. I'd rather not support that one, but would help out in resolving the issue with the other. Can you provide more details?

**Comment by hawkeyexp** [comment]
the multicam plugin is a bit loveless since a while and has some bugs also reported from others....

i created an issue for that https://github.com/mikedmor/OctoPrint_MultiCam/issues/38

But my solutions is now a mix: multicam to set all cams to make genrral available also for remote tools and your multicamviewer to create a nice gui setup with ui customizer to show both cams and controls in one tab :-)

**Comment by jneilliii** [comment]
I took a quick look at that plugin's code and it seems pretty straight forward, so not quite sure what might be causing that to happen. I'd have to look at the js side, but it might be it's settings migration freaking out in some way. Best I could tell during my testing was that it does store the settings like you propose in it's own settings section, once you save, it's only the defaults are being pulled from OP as the first item by default.

**Comment by hawkeyexp** [comment]
I think we can close this...
